version: "3.9"
services:
  chat-groups:
    image: chat-groups-api
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: chat-groups-api
      POSTGRES_PASSWORD: monopatin
      POSTGRES_DB: chat-groups
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0.2
    ports:
      - "6379:6379"